[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.69.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public,max-age=60"
    X-Frame-Options = "DENY"
    X-Xss-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"
    Report-To = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {"url":"https://cloudauthority.report-uri.com/a/d/g"}
      ],"include_subdomains":true}'''
    NEL = '''{
      "report_to":"report-uri",
      "max_age":31536000,
      "include_subdomains":true
    }'''
    Content-Security-Policy = "form-action https"
    Content-Security-Policy-report-only = '''
    default-src 'self';
    script-src 'self' cdnjs.cloudflare.com softveda.disqus.com *.google-analytics.com ;
    style-src 'self' cdnjs.cloudflare.com ;
    img-src 'self' data: cloudauthority.dev *.google-analytics.com ;
    font-src 'self' *.fontawesome.com cdnjs.cloudflare.com fonts.gstatic.com ;    
    report-to default;'''

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[headers]]
  # Override cache duration for assets with periods in the filename (i.e. static assets)
  for = "/*.*"
  [headers.values]
  cache-control = "public,max-age=86400"
